version: '3.8'

services:
  kataribe:
    build:
      context: ./kataribe
      dockerfile: ./Dockerfile
    volumes:
      - ./kataribe/kataribe-config:/workdir
      - ./kataribe/webserver-log:/logs

  slowquery:
    image: mysql:8.0.34-debian
    working_dir: /workdir 
    volumes:
      - ./mysql-slowquery:/workdir/mysql-slowquery

  pprof:
    build: 
      context: ./pprof
      dockerfile: ./Dockerfile
    volumes:
      - ./pprof/profilefiles:/tmp/profile
      - ./pprof/output:/tmp/output
    expose:
      - "8888"
    network_mode: host

  alp:
    build: 
      context: ./alp
      dockerfile: ./Dockerfile
    volumes:
      - ./alp:/workdir/alp
  
  ansible:
    build: 
      context: ./ansible
      dockerfile: ./Dockerfile

  pt-query-digest:
    build: 
      context: ./pt-query-digest
      dockerfile: ./Dockerfile
    volumes:
      - ./mysql-slowquery:/workdir/mysql-slowquery

  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - prom_data:/prometheus
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./prometheus-grafana/grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
      - ./prometheus-grafana/grafana/dashboard.yaml:/var/lib/grafana/dashboards

  deploy-test-1:
    build:
      context: ./deploy-test
      dockerfile: ./Dockerfile
    ports:
      - "2222:22"
  
  deploy-test-2:
    build:
      context: ./deploy-test
      dockerfile: ./Dockerfile
    ports:
      - "2223:22"

volumes:
  prom_data: