version: '3.8'

services:
  kataribe:
    build:
      context: ./kataribe
      dockerfile: ./Dockerfile
    volumes:
      - ./kataribe/kataribe-config:/workdir
      - ./kataribe/webserver-log:/logs

  slowquery:
    image: mysql:8.0-debian
    volumes:
      - ./mysql-slowquery/mysql-slowquery-log:/var/log/slowquery-log

  pprof:
    build: 
      context: ./pprof
      dockerfile: ./Dockerfile
    volumes:
      - ./pprof/profilefiles:/tmp/profile
      - ./pprof/output:/tmp/output
    expose:
      - "8888"
    network_mode: host

  alp:
    build: 
      context: ./alp
      dockerfile: ./Dockerfile
  
  ansible:
    build: 
      context: ./ansible
      dockerfile: ./Dockerfile

  pt-query:
    build: 
      context: ./pt-query-digest
      dockerfile: ./Dockerfile
  
  deploy-test:
    build:
      context: ./deploy-test
      dockerfile: ./Dockerfile
    ports:
      - "2222:22"