---
- name: Ping servers
  ansible.builtin.ping:
  register: ping_res

- block:
  - name: Check res in block
    debug:
      msg: "{{ping_res}}"
  - name: Check res in block 
    debug:
      msg: "{{ping_res}}"
    when: extract_res.changed

- name: Check res
  debug:
    msg: "{{ping_res}}"