---
- name: Ping servers
  ansible.builtin.ping:
  register: ping_res
  changed_when: true
  notify: Handler invoked by name
  tags: check-res
  
- name: Check res
  debug:
    msg: "{{ping_res}}"
  changed_when: true
  notify: handler invoked by listener