- name: Print all available facts
  ansible.builtin.debug:
    var: ansible_facts

- name: create install dir for node_exporter
  file:
    path: ~/node_exporter
    state: directory

- name: create working dir for node_exporter
  file:
    path: /opt/node_exporter
    state: directory

- name: download node_exporter
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v1.7.0/node_exporter-1.7.0.linux-amd64.tar.gz
    dest: ~/node_exporter

- name: extract node_exporter
  unarchive:
    remote_src: true
    src: ~/node_exporter/node_exporter-1.7.0.linux-amd64.tar.gz
    dest: ~/node_exporter
  register: extract_res

- name: create link
  file:
    path: /bin/node_exporter
    state: link
    src: ~/node_exporter/node_exporter-1.7.0.linux-amd64/node_exporter
  become: true

- name: start node_exporter
  command: /bin/node_exporter
  async: 45
  poll: 0
