# roleのprerequisitesを定義できる
# あるroleを実行するとき，自動的にdependenciesで指定されたroleが実行される
# 暗黙的な実行になるのでよほど冪等に実装できていない限りplaybookに明記した方がいいのでは
---
dependencies:
  - role: common

# 基本的にroleはvariableが異なる場合を除いて一回しか実行されない
## 冪等で実装されている前提なので
# 複数回実行したい場合は，allow_duplicatesで設定
allow_duplicates: true